spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring_reactive
    username: username
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5432/spring_reactive
    user: username
    password: password
    locations: classpath:db/migration

